# Generated by Django 5.2 on 2025-05-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('History', 'History'), ('Autobiography', 'Autobiography'), ('Science fiction', 'Science fiction'), ('Adventure fiction', 'Adventure fiction'), ('Biography', 'Biography'), ('Poetry', 'Poetry'), ('Romance novel', 'Romance novel'), ('others', 'others')], default='others', max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_app.seller')),
            ],
        ),
    ]
