# Generated by Django 5.2 on 2025-05-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='cover',
            field=models.ImageField(default=1, upload_to='bookcovers/'),
            preserve_default=False,
        ),
    ]
